sudo: false
language: c++
cache:
  directories:
  - cppunit-1.13.2 
before_install:
  - sh ./scripts/getCppUnit.sh
  - . scripts/exports.sh
  - pip install --user cpp-coveralls
script:
  - make 
  - make run_tests
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
